definitions:
  main.DelRuleReq:
    properties:
      cmd:
        type: string
    required:
    - cmd
    type: object
  main.Rule:
    properties:
      cmd:
        type: string
      regex:
        type: string
      remote_addr:
        type: string
    required:
    - cmd
    - remote_addr
    type: object
  main.SelectorFuncName:
    properties:
      func_name:
        type: string
    required:
    - func_name
    type: object
  main.SystemConfig:
    properties:
      admin_qq:
        type: string
      cqhttp_address:
        type: string
      prefix:
        items:
          type: string
        type: array
      secret:
        type: string
    required:
    - admin_qq
    - cqhttp_address
    - prefix
    - secret
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
  selector.Node:
    properties:
      id:
        type: string
      remote_addr:
        type: string
    required:
    - remote_addr
    type: object
info:
  contact: {}
paths:
  /api/config/get:
    get:
      description: Get gateway's system config
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get system config
      tags:
      - config
  /api/config/modify:
    post:
      consumes:
      - application/json
      description: 'Modify gateway''s system config, include: "CQHTTP_API_ADDRESS",
        "CQHTTP_SECRET", "ADMIN_QQ", "CMD PREFIX"'
      parameters:
      - description: config struct
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/main.SystemConfig'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Modify config
      tags:
      - config
  /api/node/add:
    post:
      consumes:
      - application/json
      description: Add a proxy remote node into the gateway's selector
      parameters:
      - description: 'Proxy node''s remote address, eg: 127.0.0.1:8081'
        in: body
        name: node
        required: true
        schema:
          $ref: '#/definitions/selector.Node'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Add Proxy Node
      tags:
      - Selector
  /api/node/getAll:
    get:
      description: Get all proxy nodes and current selector's function
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get all nodes
      tags:
      - Selector
  /api/node/modifySelector:
    post:
      consumes:
      - application/json
      description: 'Change gateway''s selector method, supported: "random", "round_robin",
        "hash", "weight"'
      parameters:
      - description: Load balance algorithm name
        in: body
        name: selector
        required: true
        schema:
          $ref: '#/definitions/main.SelectorFuncName'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Modify Selector
      tags:
      - Selector
  /api/node/remove:
    post:
      consumes:
      - application/json
      description: Delete a proxy node
      parameters:
      - description: Node's remote address
        in: body
        name: node
        required: true
        schema:
          $ref: '#/definitions/selector.Node'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Delete Node
      tags:
      - Selector
  /api/rule/add:
    post:
      consumes:
      - application/json
      description: Add a command rule
      parameters:
      - description: 'Proxy command rule''s cmd and remote address, eg: remote_addr:
          127.0.0.1:8081, cmd: help'
        in: body
        name: node
        required: true
        schema:
          $ref: '#/definitions/main.Rule'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Add Command Rule
      tags:
      - Rule
  /api/rule/getAll:
    get:
      description: Get all command rules
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get all rules
      tags:
      - Rule
  /api/rule/modify:
    post:
      consumes:
      - application/json
      description: Modify a command rule
      parameters:
      - description: Rule's struct
        in: body
        name: node
        required: true
        schema:
          $ref: '#/definitions/main.Rule'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Modify Rule
      tags:
      - Rule
  /api/rule/remove:
    post:
      consumes:
      - application/json
      description: Delete a command rule
      parameters:
      - description: Rule's cmd
        in: body
        name: node
        required: true
        schema:
          $ref: '#/definitions/main.DelRuleReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Delete Rule
      tags:
      - Rule
swagger: "2.0"
